version: "3"
services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    expose:
      - "9000"
    environment:
      - ASR_MODEL=medium
    restart: on-failure
    volumes:
      - ./models:/root/.cache/whisper
  server:
    build:
      context: packages/server
      dockerfile: Dockerfile
    environment:
      - WORK_DIR=/tmp/scribe/tmp
      - WHISPER_URL=http://whisper:9000
      - PARALLELISM=2
    volumes:
      - ./library:/tmp/library
    ports:
      - "3000:3000"
  client:
    build:
      context: packages/client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - whisper
    restart: on-failure
    ports:
      - "4000:4000"
